s = "hello this 1 is string Practice code   "
m = len(s)
print(s.capitalize())
print(s.casefold())
print(s.center(5))
print(s.count("s"))
print(s.encode())
print(s.endswith("code"))
print(s.partition("s"))
print(s.index("s"))
print(s.strip())
print(s.split("s"))
print(s[0:])
